//
// PriceMdl.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PriceMdl: JSONEncodable {

    public enum Store: String { 
        case KauflandSagului = "KAUFLAND_SAGULUI"
        case KauflandLazar = "KAUFLAND_LAZAR"
        case ProfiComplex = "PROFI_COMPLEX"
        case Hacktm = "HACKTM"
    }
    
    public var price: Double?
    public var product: ProductMdl?
    public var profile: ProfileMdl?
    public var createdAt: NSDate?
    public var store: Store?
    public var imageUrl: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["price"] = self.price
        nillableDictionary["product"] = self.product?.encodeToJSON()
        nillableDictionary["profile"] = self.profile?.encodeToJSON()
        nillableDictionary["createdAt"] = self.createdAt?.encodeToJSON()
        nillableDictionary["store"] = self.store?.rawValue
        nillableDictionary["imageUrl"] = self.imageUrl
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
