//
// ProductMdl.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProductMdl: JSONEncodable {

    public enum Category: String { 
        case Lactate = "LACTATE"
        case Fructe = "FRUCTE"
        case Carne = "CARNE"
        case Dulciuri = "DULCIURI"
    }
    
    public enum Store: String { 
        case KauflandSagului = "KAUFLAND_SAGULUI"
        case KauflandLazar = "KAUFLAND_LAZAR"
        case ProfiComplex = "PROFI_COMPLEX"
    }
    
    public var id: String?
    public var name: String?
    public var barcode: String?
    public var category: Category?
    public var store: Store?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["barcode"] = self.barcode
        nillableDictionary["category"] = self.category?.rawValue
        nillableDictionary["store"] = self.store?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
