//
// ProductResponseMdl.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ProductResponseMdl: JSONEncodable {

    public var productMdl: ProductMdl?
    public var bestPrice: PriceMdl?
    public var otherPrices: [PriceMdl]?
    public var totalSum: Double?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["productMdl"] = self.productMdl?.encodeToJSON()
        nillableDictionary["bestPrice"] = self.bestPrice?.encodeToJSON()
        nillableDictionary["otherPrices"] = self.otherPrices?.encodeToJSON()
        nillableDictionary["totalSum"] = self.totalSum
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
