source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '8.1'
# Uncomment this line if you're using Swift
use_frameworks!

workspace ‘ShopCompare’

pod 'Alamofire'
pod 'AlamofireImage', '~> 2.0'