//
// RestAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension SwaggerClientAPI {
    
    public class RestAPI: APIBase {
    
        /**
         
         Add product
         
         - GET /rest/add
         - 
         - examples: [{contentType=application/json, example={
  "name" : "aeiou",
  "id" : "aeiou",
  "store" : "aeiou",
  "category" : "aeiou",
  "barcode" : "aeiou"
}}]
         
         - parameter gpsPosition: (query) gps position.
         - parameter barcode: (query) barcode.
         - parameter name: (query) name.
         - parameter category: (query) category.

         - returns: RequestBuilder<ProductMdl> 
         */
        public class func addProduct(gpsPosition gpsPosition: String, barcode: String, name: String, category: String) -> RequestBuilder<ProductMdl> {
            let path = "/rest/add"
            let URLString = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [
                "gpsPosition": gpsPosition,
                "barcode": barcode,
                "name": name,
                "category": category
            ]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<ProductMdl>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
        }
    
        /**
         
         Find product
         
         - GET /rest/find
         - 
         - examples: [{contentType=application/json, example=[ {
  "name" : "aeiou",
  "id" : "aeiou",
  "store" : "aeiou",
  "category" : "aeiou",
  "barcode" : "aeiou"
} ]}]
         
         - parameter category: (query) search category.
         - parameter query: (query) search query.

         - returns: RequestBuilder<[ProductMdl]> 
         */
        public class func findProduct(category category: String, query: String) -> RequestBuilder<[ProductMdl]> {
            let path = "/rest/find"
            let URLString = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [
                "category": category,
                "query": query
            ]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<[ProductMdl]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
        }
    
    }
}
